version: '3'
services:
    mirakurun:
        build:
            context: mirakurun
        container_name: mirakurun
        #cap_add:
        #    - SYS_NICE
        #    - SYS_ADMIN
        privileged: true
        ports:
            - "40772:40772"
            - "9229:9229"
        #extra_hosts:
            #- "bondriverproxy:172.17.0.1" # BonDriverProxy Server
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mirakurun/conf:/usr/local/etc/mirakurun
            - ./mirakurun/db:/usr/local/var/db/mirakurun
        environment:
            TZ: "Asia/Tokyo"
        devices:
            - /dev/pt3video0:/dev/pt3video0
            - /dev/pt3video1:/dev/pt3video1
            - /dev/pt3video2:/dev/pt3video2
            - /dev/pt3video3:/dev/pt3video3
            - /dev/pt3video4:/dev/pt3video4
            - /dev/pt3video5:/dev/pt3video5
            - /dev/pt3video6:/dev/pt3video6
            - /dev/pt3video7:/dev/pt3video7
            - /dev/px4video0:/dev/px4video0
            - /dev/px4video1:/dev/px4video1
            - /dev/px4video2:/dev/px4video2
            - /dev/px4video3:/dev/px4video3
            - /dev/px4video4:/dev/px4video4
            - /dev/px4video5:/dev/px4video5
            - /dev/px4video6:/dev/px4video6
            - /dev/px4video7:/dev/px4video7
            - /dev/dvb:/dev/dvb
            #- /dev/bus/usb/00x/00x # card reader
        restart: always

    mysql:
        image: mariadb:10.4
        container_name: mysql
        volumes:
            - mysql-db:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --performance-schema=false --expire_logs_days=1
        restart: always

    epgstation:
        build:
            context: epgstation
            args:
                - CPUCORE=2
        container_name: epgstation
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/localtime:/etc/localtime:ro
            - ./epgstation/config:/usr/local/EPGStation/config
            - ./epgstation/data:/usr/local/EPGStation/data
            - ./epgstation/thumbnail:/usr/local/EPGStation/thumbnail
            - ./epgstation/logs:/usr/local/EPGStation/logs
            - ./epgstation/recorded:/usr/local/EPGStation/recorded
            #- /recdisk/share/recorded:/usr/local/EPGStation/recorded
            #- /recdisk/share/encode_tmp:/usr/local/EPGStation/encode_tmp
        environment:
            TZ: "Asia/Tokyo"
        links:
            - mirakurun:mirakurun
            - mysql:mysql
        ports:
            - "8888:8888"
            - "8889:8889"
        #user: "1000:1000"
        restart: always

volumes:
    mysql-db:
        driver: local

